This will allow us to run comparision checks against tarballs vai checksums by comparing S3Object metatdata against the local dir needed to be cached. Signed-off-by: Nathaniel Kierpiec <nkierpiec@chef.io>

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -23,19 +23,39 @@ do
 
   s3_bucket="s3://${BUILDKITE_PLUGIN_CACHE_S3_BUCKET}/${BUILDKITE_PIPELINE_SLUG}/${label}"
 
-  aws s3 ls ${s3_bucket}/${filename}.tar.gz
-  rc=$?
-  if [[ ${rc} -eq 0 ]]; then
-    echo "--- :aws: :amazon-s3: cp ${filename}"
-    aws s3 cp "${s3_bucket}/${filename}.tar.gz" "."
-    
-    echo "--- untar into ${path}"
-    if [[ $OSTYPE != "msys" ]] ; then
-      sudo tar -xzf ${filename}.tar.gz	
-    else	
-      tar -xzf ${filename}.tar.gz	
+  # check if the tar file exists
+  if aws s3 ls ${s3_bucket}/${filename}.tar.gz; then
+    echo "aws s3 cp ${filename}"
+    aws s3 cp ${s3_bucket}/${filename}.tar.gz .
+
+    echo "comparing checksums..."
+    md5s3object=$(aws s3api head-object --bucket ${BUILDKITE_PLUGIN_CACHE_S3_BUCKET} --key ${BUILDKITE_PIPELINE_SLUG}/${label}/${filename}.tar.gz | jq -r '.Metadata.md5checksum')
+    md5localobject=$(openssl md5 ${filename}.tar.gz |base64)
+
+    if [[ ${md5s3object} != "null" ]]; then
+      if [[ ${md5s3object} == ${md5localobject} ]]; then
+        echo "untar into ${path}"
+        if [[ $OSTYPE != "msys" ]]; then
+          sudo tar -xzf ${filename}.tar.gz
+        else
+          tar -xzf ${filename}.tar.gz
+        fi
+      else
+        echo "checksums differ, skipping extraction"
+      fi
+    else
+      if ! tar -tf ${filename}.tar.gz > /dev/null; then
+        echo "tarball cannot be opened, may be corrupted, skipping extraction"
+      else
+        echo "untar into ${path}"
+        if [[ $OSTYPE != "msys" ]]; then
+          sudo tar -xzf ${filename}.tar.gz
+        else
+          tar -xzf ${filename}.tar.gz
+        fi
+      fi
     fi
-  else 
-    echo "-- skipping :aws: :amazon-s3: cp as ${filename}.tar.gz does not exist in ${s3_bucket}"
+  else
+    echo "skipping aws s3 cp as ${filename}.tar.gz does not exist in ${s3_bucket}"
   fi
 done
